server:
  port: 8081
  servlet:
    context-path: /clients

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mcb_pet_project
    username: postgres
    password: Nihongonodeska1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers:
      localhost: 9092
    consumer:
      group-id: "transfer_consumer"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'